export const idRouter = Object.freeze({
	home: "/",
	contact: "/contact",
	blog: "/blog",
	login: "/login",
	userLogin: "/user-login",
	forgotPassword: "/forgot-password",
	verifyEmail: "/verify-email",
	courses: "courses",
	document: "document",
	documentDetail: "/document/:id",
	careerDetail: "/career/:id",
	admin: "/admin",
	adminDashboard: "dashboard",
	adminInbox: "inbox",
	adminCalendar: "calendar",
	adminCareers: "careers",
	adminContact: "contact",
	adminSettings: "settings",
	adminPosts: "posts",
	adminPostWrite: "posts/write",
	solutionDetail: "/solution/:id",
});
