export const idRouter = Object.freeze({
	home: "/",
	about: "/about",
	contact: "/contact",
	service: "/services",
	solution: "/solution",
	career: "/career",
	blog: "/blog",
	demo: "/demo",
	vision: "/vision",
	login: "/login",
	courses: "courses",
	document: "document",
	documentDetail: "/document/:id",
	careerDetail: "/career/:id",
	admin: "/admin",
	adminDashboard: "dashboard",
	adminInbox: "inbox",
	adminCalendar: "calendar",
	adminCareers: "careers",
	adminContact: "contact",
	adminSettings: "settings",
	adminPosts: "posts",
	adminPostWrite: "posts/write",
	solutionDetail: "/solution/:id",
});
